name: Docker build and publish

on:
    push:
        branches:
            - master

jobs: 
    build-and-push:
      runs-on: ubuntu-latest
      steps: 
          - name: Clone code
            uses: actions/checkout@v2

          - name: Login to Docker Hub
            run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

          - name: Build Docker Image
            run: docker build -t lilpan6969/viruelachangoapi:${{ github.sha }} .

          - name: Tag Latest
            run: docker tag lilpan6969/viruelachangoapi:${{ github.sha }} lilpan6969/viruelachangoapi:latest
            
          - name: Push Docker Image
            run: |
              docker push lilpan6969/viruelachangoapi:${{ github.sha }}
              docker push lilpan6969/viruelachangoapi:latest